spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/test-post?useSSL=false&characterEncoding=utf-8
    username: root
    password: 770212
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update

